language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t image-docker-react -f Dockerfile.dev .
    
script:
 - docker run -e CI=true image-docker-react npm run test -- --coverage